# Generated by Django 2.0.13 on 2019-05-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('I', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado'), ('D', 'Domingo')], max_length=1)),
                ('intervalo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apodo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('avatar', models.CharField(max_length=400)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('amigos', models.ManyToManyField(related_name='_jugador_amigos_+', to='app.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasJugadas', models.PositiveIntegerField()),
                ('estadisticas', models.TextField(blank=True, null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Juego')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorJuegoLogro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField()),
                ('jugadorJuego', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.JugadorJuego')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorRecompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=400)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logros', to='app.Juego')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('jugador_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensajes_enviados', to='app.Jugador')),
                ('jugador_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensajes_recibidos', to='app.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigencia', models.DateField()),
                ('minJugadores', models.IntegerField(default=1)),
                ('maxJugadores', models.IntegerField(default=1)),
                ('completada', models.BooleanField(default=False)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Jugador')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='misiones', to='app.Juego')),
                ('logro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='misiones', to='app.Logro')),
            ],
        ),
        migrations.CreateModel(
            name='MisionRecompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Mision')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAviso', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptada', models.BooleanField(default=False)),
                ('jugador_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudesAmistad_enviadas', to='app.Jugador')),
                ('jugador_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudesAmistad_recibidas', to='app.Jugador')),
            ],
        ),
        migrations.AddField(
            model_name='misionrecompensa',
            name='recompensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Recompensa'),
        ),
        migrations.AddField(
            model_name='mision',
            name='recompensas',
            field=models.ManyToManyField(through='app.MisionRecompensa', to='app.Recompensa'),
        ),
        migrations.AddField(
            model_name='jugadorrecompensa',
            name='recompensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Recompensa'),
        ),
        migrations.AddField(
            model_name='jugadorjuegologro',
            name='logro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Logro'),
        ),
        migrations.AddField(
            model_name='jugadorjuego',
            name='logros',
            field=models.ManyToManyField(through='app.JugadorJuegoLogro', to='app.Logro'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='juegos',
            field=models.ManyToManyField(through='app.JugadorJuego', to='app.Juego'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='misionesAdquiridas',
            field=models.ManyToManyField(related_name='cazaRecompensas', to='app.Mision'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='notificaciones',
            field=models.ManyToManyField(to='app.Notificacion'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='recompensas',
            field=models.ManyToManyField(through='app.JugadorRecompensa', to='app.Recompensa'),
        ),
        migrations.AddField(
            model_name='dia',
            name='jugador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarioJuego', to='app.Jugador'),
        ),
        migrations.AddField(
            model_name='dia',
            name='jugador_juego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarioJuego', to='app.JugadorJuego'),
        ),
    ]
